
# This is a basic workflow to help you get started with Actions

name: Get Chicago latest crime data daily

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 12 * * *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render:
    name: Get and compile recent crimes data
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install gdal
        run: |
          brew install gdal
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("sf","zoo","janitor","tidyverse","readxl","leaflet","leaflet.extras","leaflet.providers","htmlwidgets","htmltools"))'
      - name: Get daily crime data and compile
        run: Rscript scripts/process_chicago_crime.R
      - name: Render all markdowns from central script
        run: Rscript scripts/run_markdowns.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New crime data collected' || echo "No changes"
          git push origin || echo "No changes to commit"
